### ISSUE TITLE
Spectral not handling keys containing @

### ISSUE THREAD

**Issue by singhtejpal11** [stoplightio/spectral#1456]
This refactor will help us to allow below schema:
'@customerLocation':
 type: string
 example: "https://google.com"
 format: uri
 description: A URI to a JSON-Schema file that defines additional attributes and relationships
 
 As of now, we are getting below exception with this-
 TypeError: Unknown value type customerTy
    at JSONPath._trace (/*/node_modules/jsonpath-plus/dist/index-umd.js:766:17)
    at /*/node_modules/jsonpath-plus/dist/index-umd.js:745:23
    at /*/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/*/node_modules/jsonpath-plus/dist/index-umd.js:908:24)
    at JSONPath._trace (/*/node_modules/jsonpath-plus/dist/index-umd.js:743:12)
    at JSONPath._trace (/*/node_modules/jsonpath-plus/dist/index-umd.js:698:19)
    at /*/node_modules/jsonpath-plus/dist/index-umd.js:706:23
    at /*/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)

**Comment by P0lip** [comment]
Hey!
This is going to be fixed by https://github.com/stoplightio/spectral/pull/1785
