### ISSUE TITLE
Support the --version command line argument

### ISSUE THREAD

**Issue by DavidBiesack** [stoplightio/spectral#2078]
**Describe the bug**

The tool has a `--version` option but returns `0.0.0` instead of the current version.

**To Reproduce**

```bash
$ spectral --version
0.0.0
```

**Expected behavior**

```bash
$ spectral --version
6.3.0
```

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 6.3.0]
 - OS: [e.g. Mac]
 - Browser: [N/A]

**Comment by P0lip** [comment]
Hmmm, I cannot reproduce it.
How did you install Spectral? Or do you perhaps use the Docker image or the distributed binary?

**Comment by DavidBiesack** [comment]
I had installed with npm and did an update. However, that was pointed at the old repo.
When I try to install latest
```
$ npm i -g @stoplight/spectral-cli
$ type spectral
spectral is hashed (~/.nvm/versions/node/v12.18.3/bin/spectral)
$ spectral --version
internal/modules/cjs/loader.js:490
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './presets/node' is not defined by "exports" in ~/.nvm/versions/node/v12.18.3/lib/node_modules/@stoplight/spectral-cli/node_modules/@stoplight/spectral-ruleset-bundler/package.json
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/.nvm/versions/node/v12.18.3/lib/node_modules/@stoplight/spectral-cli/dist/services/linter/utils/getRuleset.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

```

and I get the same problem if I uninstall then install earlier versions such as 
@stoplight/spectral-cli@6.1.0 and @stoplight/spectral-cli@6.2.0

Only 6.0.0 works for me 
```
$ spectral --version
6.0.0
```

but that appears to be a different problem
