### ISSUE TITLE
Getting an AggregateError when using JSON custom ruleset

### ISSUE THREAD

**Issue by imsuneth** [stoplightio/spectral#2242]
I have a configuration file that includes the custom rules among other configurations. I retrieve the custom rules object (I have defined it as a const below) from the file and set it and run the linter.
```
const apiDefinition
const customRules = {
  "rules": {
    "empty-title-property": {
      "message": "Title must not be empty",
      "given": "$..title",
      "then": {
        "function": "truthy"
      }
    }
  }
};
const spectral = new Spectral();
spectral.setRuleset(customRules);
spectral.run(apiDefinition).then((result)=> {
  console.log(result);
}
```

However, I am getting this AggregateError and not sure what I am doing wrong. Could you please help?
```
AggregateError: Error running Nimma
    at Scope.destroy (scope.js:137:1)
    at Nimma.eval (eval at query (index.js:66:1), <anonymous>:17:11)
    at Nimma.query (index.js:68:1)
    at execute (runner.js:90:1)
    at Runner.run (runner.js:53:1)
    at Spectral.runWithResolved (spectral.js:60:1)
    at async Spectral.run (spectral.js:68:1)
```

**Environment (remove any that are not applicable):**
 - Library version: 1.12.2
 - OS: macOs monetrey 12.4

**Comment by LukeMccon** [comment]
I've run into this before as well, try logging the `.errors` property of the aggregate error you're receiving if you haven't already. That may give you some extra context

**Comment by imsuneth** [comment]
Thanks @LukeMccon. Here is what i found in `.errors`

Error: $ threw: ErrorWithCause("Function \"undefined\" threw an exception: then.function is not a function")
    at _callbacks.<computed> (proxy-callbacks.js:34:1)
    at Scope.emit (scope.js:109:1)
    at Nimma.eval (eval at query (index.js:66:1), <anonymous>:7:11)
    at Nimma.query (index.js:68:1)
    at execute (runner.js:90:1)
    at Runner.run (runner.js:53:1)
    at Spectral.runWithResolved (spectral.js:60:1)
    at async Spectral.run (spectral.js:68:1)

TypeError: then.function is not a function
    at lintNode (lintNode.js:24:1)
    at cb (runner.js:45:1)
    at mapped.<computed> (runner.js:93:1)
    at _callbacks.<computed> (proxy-callbacks.js:31:1)
    at Scope.emit (scope.js:109:1)
    at Nimma.eval (eval at query (index.js:66:1), <anonymous>:7:11)
    at Nimma.query (index.js:68:1)
    at execute (runner.js:90:1)
    at Runner.run (runner.js:53:1)
    at Spectral.runWithResolved (spectral.js:60:1)

**Comment by P0lip** [comment]
You cannot load a JSON ruleset this way. Spectral#setRuleset accepts only JS rulesets.

```
const { truthy } = require('@stoplight/spectral-functions');

const apiDefinition
const customRules = {
  "rules": {
    "empty-title-property": {
      "message": "Title must not be empty",
      "given": "$..title",
      "then": {
        "function": truthy
      }
    }
  }
};
const spectral = new Spectral();
spectral.setRuleset(customRules);
spectral.run(apiDefinition).then((result)=> {
  console.log(result);
}
```

This is how a correct code would look like.
Feel free to reach out in case you have some questions.

**Comment by imsuneth** [comment]
Thanks a lot @P0lip for the clarification. Is there any way right now to parse a JSON ruleset to a JS ruleset?

**Comment by LukeMccon** [comment]
@imsuneth look at the [ruleset-migrator](https://github.com/stoplightio/spectral/tree/develop/packages/ruleset-migrator) package. There should be instructions on that page, I was able to use it to move from JSON to JS rulesets.

**Comment by imsuneth** [comment]
@LukeMccon thanks a lot and i'll look into it.
