### ISSUE TITLE
Strange issue with regex: match() or regex operators

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#2269]
**Describe the bug**

When constructing a custom ruleset I've got a rule involving `@.match` and its telling me that match is not a function. It looks like nimma is being used so im trying to use other regex operators, but neither `~=` (from the README) or `=~` from (the draft RFC linked in the README) work, all giving different errors.

**To Reproduce**

1. Clone https://github.com/philsturgeon/spectral-owasp-ruleset
2. CD into the dir and run `npm run build`
3. Run this CLI command `spectral lint https://petstore.swagger.io/v2/swagger.json --ruleset=dist/ruleset.js --verbose`
4. See error for `.match`

**Expected behavior**

I'd expect this function to work, as its copied from another ruleset I made.

```ts
 "owasp:api1:2019-no-numeric-ids": {
      description:
        "OWASP API1:2019 - Use random IDs that cannot be guessed (UUIDs)",
      severity: DiagnosticSeverity.Error,
      given:
        '$.paths..parameters[*].[?(@property === "name" && (@ === "id" || @.match(/(_id|Id)$/)))]^.schema',
      then: {
        function: schema,
        functionOptions: {
          schema: {
            type: "object",
            not: {
              properties: {
                type: {
                  const: "integer",
                },
              },
            },
            properties: {
              format: {
                const: "uuid",
              },
            },
          },
        },
      },
    },
```

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

The nimma README says `Support for containments (in) and regex (~=) operators, as taken from draft-ietf-jsonpath-base-01` but that draft RFC says it should look like this: `$.a[?@.b =~ "i.*"]`. Sadly neither work.

I've tried the following JSONPath selectors:

- `'$.paths..parameters[*].[?(@property === "name" && (@ === "id" || @.match(/(_id|Id)$/)))]^.schema'`
- `'$.paths..parameters[*].[?( @property === "name" && ( @ === "id" || @ ~= "(_id|Id)$" ) )]^.schema'`
- `'$.paths..parameters[*].[?( @property === "name" && ( @ === "id" || @ =~ "(_id|Id)$" ) )]^.schema'`

Any tips on whats gone wrong here?

**Comment by P0lip** [comment]
@philsturgeon would `'$.paths..parameters[*].[?(@property === "name" && (@ === "id" || @ && @.match(/(_id|Id)$/)))]^.schema'` work?

**Comment by philsturgeon** [comment]
Sadly this doesn't fix it. 

```
Linting https://petstore.swagger.io/v2/swagger.json
evalmachine.<anonymous>:1
_$_property === "name" && (_$_v === "id" || _$_v && _$_v.match(/(_id|Id)$/))
                                                         ^

TypeError: _$_v.match is not a function
    at evalmachine.<anonymous>:1:58
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at JSONPath._eval (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:643:20)
    at /Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:420:16
    at /Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:576:7
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:575:22)
    at JSONPath._trace (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:419:10)
Error running Spectral!
Error #1: jsonPath: _$_v.match is not a function: _$_property === "name" && (_$_v === "id" || _$_v && _$_v.match(/(_id|Id)$/))
          at _eval    …ex-node-cjs.cjs:647  throw new Error('js…
          at          …ex-node-cjs.cjs:420  if (this._eval(l.re…
          at          …ex-node-cjs.cjs:576  f(m, loc, expr, val…
          at forEach
          at _walk    …ex-node-cjs.cjs:575  Object.keys(val).fo…
```

**Comment by philsturgeon** [comment]
This seems to be working now? Perhaps that magic `.[` removal helped. 

`$.paths..parameters[*][?(@property === "name" && (@ === "id" || @.match(/(_id|Id|-id)$/)))]^.schema`

**Comment by philsturgeon** [comment]
Ah no sorry, spoke too soon. apisyouwonthate style guide still has this issue. 

```
Found 18 rules (18 enabled)
Linting https://petstore.swagger.io/v2/swagger.json
evalmachine.<anonymous>:1
_$_property === "name" && (_$_v === "id" || _$_v && _$_v.match(/(_id|Id)$/))
                                                         ^

TypeError: _$_v.match is not a function
    at evalmachine.<anonymous>:1:58
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at JSONPath._eval (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:643:20)
    at /Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:420:16
    at /Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:576:7
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:575:22)
    at JSONPath._trace (/Users/phil/.asdf/installs/nodejs/16.15.1/.npm/lib/node_modules/@stoplight/spectral-cli/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:419:10)
Error running Spectral!
Error #1: jsonPath: _$_v.match is not a function: _$_property === "name" && (_$_v === "id" || _$_v && _$_v.match(/(_id|Id)$/))
          at _eval    …ex-node-cjs.cjs:647  throw new Error('js…
          at          …ex-node-cjs.cjs:420  if (this._eval(l.re…
          at          …ex-node-cjs.cjs:576  f(m, loc, expr, val…
          at forEach
          at _walk    …ex-node-cjs.cjs:575  Object.keys(val).fo…
```

**Comment by philsturgeon** [comment]
Huzzah I changed the apisyouwonthate ruleset to `$.paths..parameters[*][?(@property === "name" && (@ === "id" || @.match(/(_id|Id|-id)$/)))]^.schema` too and tests are passing.
